### ISSUE TITLE
Shockwaves Effect Letter Score with Expanded HUD

### ISSUE THREAD

**Issue by xXCrash2BomberXx** [FrozenAlex/GraphicsTweaks#2]
When having shockwaves enabled as well as the expanded HUD, the shockwaves make the letter score have the shockwaves effect similar to the healthy bar. I don't believe this behavior on the letter score was intentional as none of the other HUD elements seem to behave in the same way (although possibly due to them being higher on the screen) nor does the behavior match the PC game.

**Comment by Futuremappermydud** [comment]
This is base game behavior and not something we control
