### ISSUE TITLE
is this only compatible with 1.35? how about 1.28?

### ISSUE THREAD

**Issue by st-ivan** [FrozenAlex/GraphicsTweaks#3]
is this only compatible with 1.35? how about 1.28?

**Comment by FrozenAlex** [comment]
@st-ivan You have AnyTweaks there though. 1.28 is considered legacy now and is using an older unity build. Supporting it does not make sense for GraphicsTweaks.

**Comment by st-ivan** [comment]
hi, thanks for the quick response.. i didnt know about anytweaks mod.. i will try it.
