### ISSUE TITLE
The graphic resolution has not improved

### ISSUE THREAD

**Issue by guochuang419** [FrozenAlex/GraphicsTweaks#5]
The graphic resolution has not improved

**Comment by IamNcikName** [comment]
I have also encountered this situation. What kind of headset are you using?

**Comment by FrozenAlex** [comment]
I only heard that this issue happens on non legit beat saber. Give us more info and if it is non legit then it's not really supported and should be fixed by the person making the non legit version lel

**Comment by IamNcikName** [comment]
您好，您的邮件已收到。谢谢！

**Comment by IamNcikName** [comment]
您好，您的邮件已收到。谢谢！
