### ISSUE TITLE
Music and gameplay desync

### ISSUE THREAD

**Issue by Slooshie1** [FrozenAlex/GraphicsTweaks#7]
On Beat Saber 1.37.0, when only GraphicsTweaks is installed, there is a noticeable delay between gameplay and the music where the music is maybe 100-300 milliseconds behind the gameplay. I don't recall this happening on 1.28. The attached videos already have a small delay from Quest recording weirdness but I hope it's obvious that GraphicsTweaks makes it worse.

With GraphicsTweaks: 
https://github.com/user-attachments/assets/0531f50c-33dd-413e-bfa9-db07c12cbaee

Without GraphicsTweaks:
https://github.com/user-attachments/assets/1082845a-eb4f-4482-a196-93c077ce70eb

**Comment by FrozenAlex** [comment]
Hmm. Seems pretty strange. Could you adjust your audio offset in game settings? Also do you have different resolutions/refreshRates in menu and in game, does it affect latency in any way?

**Comment by FrozenAlex** [comment]
Also does the latency improve after you pause and unpause

**Comment by Slooshie1** [comment]
Is there such a setting to adjust audio latency? I noticed the issue at first with the resolution at 0.5x, bloom enabled, AA at 4x, and walls set to textured, but no combination of settings seemed to affect it. In the video I set it as if GraphicsTweaks was not doing anything. I haven’t tried pausing but I will try it later today and get back to you.

**Comment by FrozenAlex** [comment]
Yeah it's in vanilla audio settings

**Comment by Slooshie1** [comment]
Pausing and unpausing didn't seem to fix it from my testing, but the audio offset setting seemed to do the trick for me. Thank you
